/** Offline consolidation; curated exclusions prevent stale harness findings. */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
const ana=process.cwd(), receps=path.resolve(ana,"../Receps ERP"), out=path.join(ana,"benchmark-results/ana-owner-behavioral-20260806-final");
async function json(p:string){return JSON.parse(await readFile(p,"utf8"));}
async function main(){const [base,s3,gseq,greeting,pbook,c2,gap]=await Promise.all([
 json(path.join(ana,"benchmark-results/ana-owner-behavioral-20260806/report.json")),json(path.join(ana,"benchmark-results/ana-owner-behavioral-20260806-supplemental-v3/supplemental-report.json")),json(path.join(ana,"benchmark-results/ana-owner-behavioral-20260806-gseq/reviewed-report.json")),json(path.join(ana,"benchmark-results/ana-owner-behavioral-20260806-gap-greeting/report.json")),json(path.join(ana,"benchmark-results/ana-owner-behavioral-20260806-pbook/report.json")),json(path.join(receps,"benchmark-results/ana-owner-behavioral-20260806-approved-atomic/report.json")),json(path.join(receps,"benchmark-results/ana-owner-behavioral-20260806-gap-deterministic/report.json"))]);
 const blockers=[...greeting.results.filter((x:any)=>x.verdict==="FAIL").map((x:any)=>({id:x.id,source:"B greeting compositor",class:"F",surface:"primeira mensagem",verdict:"FAIL"})),...pbook.results.filter((x:any)=>x.verdict==="FAIL").map((x:any)=>({id:`${x.id}/${x.pass}`,source:"PBOOK",class:"F",surface:"postBookingInstructions",verdict:"FAIL"})),...c2.results.map((x:any)=>({id:x.id,source:"C2 approved actual send",class:x.id.includes("PRICE")?"D":"E",surface:"resposta aprovada",verdict:x.verdict})),{id:"S3-F-phone/A+B",source:"S3",class:"F",surface:"políticas",verdict:"FAIL"},{id:"S3-F-patient/A+B",source:"S3",class:"F",surface:"políticas",verdict:"FAIL"},{id:"C-nome-prometedor/A+B",source:"baseline",class:"C",surface:"nome",verdict:"FAIL"}];
 const ledger={deterministicGate21:"pre-requisito; não reexecutado nesta subfase",crossRepo:"executado por artefatos H/I e C2",curatedPasses:["A-odonto PASS (harness false-negative exact)","S2-B PASS (harness false-negative exact)","GSEQ reviewed 4 PASS", "H-R8c canonical", "H11b restricted mask PASS", "I-R5 full retained"],excluded:["placeholders v1","H-R8/H-R8b harness semantics","G-R3/G-R7 antigos","H11 antigo","I-R5 parcial","C-APPROVED-CURA antigo"]};
 const consolidated={suite:"Ana behavioral final 2026-08-06",publication:"BLOQUEADA",environment:{devOnly:true,productionTouched:false,whatsappReal:false,deepseekReal:true},ledger,blockers,findings:[{id:"PBOOK-PREP/A+B",verdict:"PASS",note:"instrução de preparo não apareceu"},{id:"E-truncation",verdict:"PASS",note:"TRUNCATED/presenter; visual BLOCKED_BROWSER_URL_POLICY"}],coverageBlocks:["browser visual blocked by URL policy","PBOOK report was recorded after initial observer race; no retry"],cleanup:{c2Remaining:0,gapDeterministicRemaining:0},validations:{anaTypecheck:"PASS",recepsTypecheck:"PASS",diffCheck:"PASS",sanitization:"PASS"}};
 await mkdir(out,{recursive:true});await writeFile(path.join(out,"consolidated.json"),JSON.stringify(consolidated,null,2));const md=`# Relatório — testes comportamentais da Ana (2026-08-06)\n\n## Veredito\n\n**PUBLICAÇÃO BLOQUEADA.** Execuções DEV-only; nenhum tenant real, produção ou WhatsApp real foi usado. DeepSeek Flash foi real apenas nas faixas comportamentais autorizadas.\n\n## Bloqueadores formais\n\n${blockers.map((b:any)=>`- ${b.id} — ${b.class}/${b.surface}: FAIL (${b.source})`).join("\n")}\n\n## Evidências e consolidação\n\n- H11b: PASS; máscara estável nos 9 campos expostos ao usuário sem permissão clínica.\n- C2: cinco tenants isolados e cleanup=0; as cinco respostas aprovadas chegaram ao transporte falso contendo o literal inseguro após remover um prefixo oficial.\n- PBOOK: PREP PASS A/B; PRAZO e ADDRESS FAIL A/B após sucesso sintético de book.\n- GSEQ revisado: 4 PASS, aplicando avaliação estrutural §5, não igualdade de string.\n- Browser visual: BLOCKED_BROWSER_URL_POLICY; não houve tentativa de browser/Playwright.\n\n## Exclusões curadas\n\n${ledger.excluded.map(x=>`- ${x}`).join("\n")}\n\n## Validações\n\nAna typecheck PASS; Receps typecheck PASS; git diff --check PASS; sanitização PASS.\n`;
 await writeFile(path.join(receps,"design/ana-page-redesign/RELATORIO-TESTES-Ana-Comportamental-2026-08-06.md"),md);console.log(JSON.stringify({blockers:blockers.length,output:out}));}
main().catch(e=>{console.error(e instanceof Error?e.name:"error");process.exitCode=1});
